#include "test_harness.h"

void register_util_math_tests(void);
void register_localization_tests(void);
void register_items_tests(void);
void register_dialogs_tests(void);
void register_sprite_manifest_tests(void);
void register_maze_data_tests(void);
void register_save_tests(void);
void register_save_migration_tests(void);
void register_save_reset_tests(void);
void register_input_remap_tests(void);
void register_collision_tests(void);
void register_entity_behavior_tests(void);
void register_interaction_tests(void);
void register_dialog_repeat_tests(void);
void register_time_of_day_tests(void);
void register_camera_tests(void);
void register_shadow_tests(void);
void register_validator_tests(void);
void register_game_fixture_tests(void);

int main(void) {
    printf("util_math\n");
    register_util_math_tests();
    printf("localization\n");
    register_localization_tests();
    printf("items\n");
    register_items_tests();
    printf("dialogs\n");
    register_dialogs_tests();
    printf("sprites\n");
    register_sprite_manifest_tests();
    printf("maze_data\n");
    register_maze_data_tests();
    printf("save\n");
    register_save_tests();
    register_save_migration_tests();
    register_save_reset_tests();
    printf("input\n");
    register_input_remap_tests();
    printf("collision\n");
    register_collision_tests();
    printf("entity_behaviors\n");
    register_entity_behavior_tests();
    printf("interaction\n");
    register_interaction_tests();
    printf("dialog_repeat\n");
    register_dialog_repeat_tests();
    printf("time\n");
    register_time_of_day_tests();
    printf("camera\n");
    register_camera_tests();
    printf("shadow\n");
    register_shadow_tests();
    printf("validator\n");
    register_validator_tests();
    printf("game_fixture\n");
    register_game_fixture_tests();
    TEST_SUMMARY();
}
